DROP materialized VIEW obras_val;
DROP materialized view ult_act_dir;
DROP materialized view serie_tam;
DROP INDEX Personal_Participar_idx;
DROP INDEX tipoRel_idx;
DROP INDEX idPeliObjeto_idx;
DROP INDEX generoPersonal_idx;
DROP TABLE capitulo;
DROP TABLE RelacionPeli;
DROP TABLE personaje;  
DROP TABLE actuarEn;
DROP TABLE rol; 
DROP TABLE participarEn;  
DROP TABLE genero;  
DROP TABLE obraCinem;   
DROP TABLE personal;
DROP SEQUENCE secP;  
DROP SEQUENCE secO;
DROP SEQUENCE secC;
