/* Sentencias para poblar las tablas del sistema de ligas*/

-- Inserción de los estadios
INSERT INTO ESTADIO SELECT DISTINCT ESTADIO, AFORO, FECHA_INAG 
FROM datosdb.ligahost
WHERE ESTADIO IS NOT NULL;
-- Inserción de las jornadas
INSERT INTO JORNADA SELECT DISTINCT JORNADA, INICIO_TEMPORADA, DIVISION 
FROM datosdb.ligahost
WHERE JORNADA IS NOT NULL AND INICIO_TEMPORADA IS NOT NULL 
      AND DIVISION IS NOT NULL;
-- Inserción de equipos
INSERT INTO EQUIPO SELECT DISTINCT CLUB, EQUIPO_LOCAL, NOMBRE, CIUDAD, FUNDACION, ESTADIO 
FROM datosdb.ligahost 
WHERE EQUIPO_LOCAL IS NOT NULL;
-- Inserción otros nombres de equipos
INSERT INTO OTROSNOMBRES SELECT DISTINCT EQUIPO, EQUIPO_LOCAL 
FROM datosdb.ligahost 
WHERE EQUIPO IS NOT NULL AND EQUIPO_LOCAL IS NOT NULL; 
-- Inserción de partidos
INSERT INTO PARTIDO SELECT DISTINCT GOLES_LOCAL, GOLES_VISITANTE, TO_NUMBER(NULL), TO_NUMBER(NULL),    
                                    EQUIPO_LOCAL, EQUIPO_VISITANTE, JORNADA, INICIO_TEMPORADA, 
                                    DIVISION 
FROM datosdb.ligahost 
WHERE GOLES_LOCAL IS NOT NULL AND GOLES_VISITANTE IS NOT NULL AND EQUIPO_LOCAL IS NOT NULL 
      AND EQUIPO_VISITANTE IS NOT NULL AND JORNADA IS NOT NULL AND INICIO_TEMPORADA IS NOT NULL 
      AND DIVISION IS NOT NULL; 
